//LIST OF Pateint
export const PATEINT_GET_DATA_SUCCESS = "PATEINT_GET_DATA_SUCCESS";
export const PATEINT_GET_DATA_ERROR = "PATEINT_GET__DATA_ERROR";

//LIST OF Doctor
export const DOCTOR_GET_DATA_SUCCESS = "DOCTOR_GET_DATA_SUCCESS";
export const DOCTOR_GET_DATA_ERROR = "DOCTOR_GET__DATA_ERROR";

export const SET_CASE_OPEN = 'SET_CASE_OPEN';

export const SET_CURRENT_CASE = 'SET_CURRENT_CASE';
export const CLEAR_CURRENT_CASE = 'CLEAR_CURRENT_CASE';

// videoCallActions.js
export const VIDEO_CALL_NOTIFICATION_SENT = 'VIDEO_CALL_NOTIFICATION_SENT';
export const VIDEO_CALL_RESOURCE_ID_RECEIVED = 'VIDEO_CALL_RESOURCE_ID_RECEIVED';
export const VIDEO_CALL_STARTED = 'VIDEO_CALL_STARTED';
export const VIDEO_CALL_STOPPED = 'VIDEO_CALL_STOPPED';
export const VIDEO_CALL_FAILED = 'VIDEO_CALL_FAILED';

export const VIDEO_CALL_STOP_SUCCESS = 'VIDEO_CALL_STOP_SUCCESS';
export const VIDEO_CALL_STOP_FAILED = 'VIDEO_CALL_STOP_FAILED';


// Action creators for each stage of the video call
